CREATE TABLE URL_Schema (
  id INT PRIMARY KEY AUTO_INCREMENT,
  short_id VARCHAR(255) UNIQUE NOT NULL,
  redirect_url TEXT NOT NULL,
  visit_history TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);